#!/usr/bin/python3
import os
import pathlib
import subprocess
import tempfile


REPOS = {
    "devel": "gicmo/dot-devel.git",
    "emacs": "gicmo/dot-emacs.git",
    "files": "gicmo/dot-files.git",
    "fish": "gicmo/dot-fish.git",
    "homeshick": "andsens/homeshick.git"
}


HS_SCRIPT = r"""#!/bin/bash
source ~/.homesick/repos/homeshick/homeshick.sh
homeshick -b -f link
"""


def clone(repo, dest):

    if repo.startswith("gicmo"):
        repo = f"git@github.com:{repo}"
    else:
        repo = f"https://github.com/{repo}"

    subprocess.run(["git", "clone", "--recursive", repo, dest],
                   check=True)


def link():
    with tempfile.TemporaryDirectory() as tmp:
        script = pathlib.Path(tmp, "script.sh")
        with open(script, "w") as f:
            f.write(HS_SCRIPT)
        script.chmod(0o770)
        subprocess.run(["/bin/bash", script], check=True)


def main():
    home = os.getenv("HOME")
    for repo, url in REPOS.items():
        print(f"{repo} -> {url}")
        dest = os.path.join(home, ".homesick", "repos", repo)
        if os.path.exists(dest):
            continue
        clone(url, dest)

    link()


if __name__ == "__main__":
    main()
